/**
 * Everything about installing and running the git hooks: the generated
 * dispatcher file, locating/chaining an existing `core.hooksPath`, and the
 * `hook <name>` handlers themselves (pre-commit/prepare-commit-msg/
 * post-commit/post-rewrite) with their `$GIT_DIR` state files.
 *
 * The `hook` handler is the one thing that runs inside someone's commit, so
 * it is written to fail open: a hard budget, one-line stderr warning, exit 0
 * whatever happens. See `commands/repo.ts` for `attributeCommit` and the
 * other selection/attribution plumbing this module builds on.
 */

import fs from 'node:fs';
import path from 'node:path';

import type { LinkedEntry } from '../attribution';
import { canonicalPath } from '../fsutil';
import * as git from '../git';
import { arr, errorMessage, rec, str } from '../json';
import { entryPoint } from '../paths';
import type { CommitRole } from '../records';
import { decodeFileEvidence } from '../records';
import { addCommitToGids, allRecords, remapCommits } from '../sessionRecords';
import { ensureConfig, findRepoRoot, gitDirOf, STORE_DIR, type StoreConfig } from '../store';
import { type CommandArgs, type Ctx, err } from '../util';
import { attributeCommit, isPartialCommit, positionalsAfter, regenerate, writeRecords } from './repo';

// DEVIATION from DESIGN.md: `pre-commit` is in the set too. Staging files from
// prepare-commit-msg does NOT put them in the commit - git has already read
// the index by then - and DESIGN.md requires the records to land in the same
// commit, so the store write + `git add` happen in pre-commit and
// prepare-commit-msg only writes the trailers (re-doing the write when
// pre-commit was bypassed).
export const HOOK_NAMES: readonly string[] = [
  'pre-commit',
  'prepare-commit-msg',
  'post-commit',
  'post-rewrite',
];

/**
 * A generated hook file: a tiny Node script that hands off to
 * `promptlog dispatch <name>` in the same bundle (see `commands/dispatch.ts`
 * for the actual logic). Node, not `sh`, so hooks run wherever Node and git
 * run, including Git for Windows (which invokes a hook file through its
 * shebang). `chainDir` is the hooks directory core.hooksPath pointed at
 * before promptlog took it over, or '' when there was none - see
 * DESIGN.md "Hooks".
 *
 * Fails open, always (DESIGN.md rule): when `bakedPath` is missing - a moved
 * or uninstalled promptlog - a bare `require()` would throw and could abort
 * the commit, so this checks `fs.existsSync` first and falls back to
 * locating `promptlog` on PATH itself: scanning each PATH entry with
 * `fs.existsSync`, trying every `PATHEXT` suffix on win32 (a shim is usually
 * `promptlog.cmd`, not a bare `promptlog`) or the bare name elsewhere - then
 * spawning it WITHOUT a shell. A shell was tried first; on Windows, `cmd.exe`
 * resolving a missing command prints its own "not recognized" error and
 * exits 1 - a status indistinguishable from `promptlog` itself failing - and
 * status 1 aborts the commit, the exact thing this fallback exists to
 * prevent. Finding the binary ourselves means "not found" is known before
 * spawning anything, so that case can warn once and exit 0 instead. The one
 * trade-off: in the not-found case any chained third-party hook (husky,
 * lefthook, a previous core.hooksPath) is skipped along with promptlog's own
 * work, since `dispatch` - which does the chaining - never got to run.
 */
function hookBody(hookName: string, chainDir: string | null): string {
  return [
    '#!/usr/bin/env node',
    '// promptlog git hook dispatcher (generated by `promptlog init`; do not edit)',
    `const bakedPath = ${JSON.stringify(entryPoint())};`,
    `const hookName = ${JSON.stringify(hookName)};`,
    `const chainDir = ${JSON.stringify(chainDir || '')};`,
    "const fs = require('fs');",
    'if (fs.existsSync(bakedPath)) {',
    "  process.argv.splice(2, 0, 'dispatch', hookName, '--chain-dir', chainDir);",
    '  require(bakedPath);',
    '} else {',
    "  const path = require('path');",
    "  const exts = process.platform === 'win32' ? (process.env.PATHEXT || '.EXE;.CMD;.BAT').split(';') : [''];",
    "  const dirs = (process.env.PATH || '').split(path.delimiter);",
    '  const candidates = [];',
    "  for (const dir of dirs) for (const ext of exts) candidates.push(path.join(dir, 'promptlog' + ext));",
    '  const found = candidates.find((c) => fs.existsSync(c));',
    '  if (found) {',
    "    const { spawnSync } = require('child_process');",
    "    const args = ['dispatch', hookName, '--chain-dir', chainDir, ...process.argv.slice(2)];",
    "    const r = spawnSync(found, args, { stdio: 'inherit' });",
    '    process.exit(r.status == null ? 0 : r.status);',
    '  }',
    '  process.stderr.write(\'promptlog: hook skipped, \' + bakedPath + " is missing and no promptlog on PATH; run \\`promptlog init\\` again\\n");',
    '  process.exit(0);',
    '}',
    '',
  ].join('\n');
}

/** The marker every dispatcher we write carries (see hookBody() above). */
const DISPATCHER_MARKER = 'promptlog git hook dispatcher';

/** Does `dir/prepare-commit-msg` hold one of OUR dispatchers? */
export function holdsOurDispatchers(dir: string): boolean {
  try {
    return fs.readFileSync(path.join(dir, 'prepare-commit-msg'), 'utf8').includes(DISPATCHER_MARKER);
  } catch {
    return false;
  }
}

/**
 * The hooks directory git actually consults for `root`, as an absolute
 * path, or null when core.hooksPath is unset at every scope. `--path` makes
 * git expand a leading `~`; a relative value is relative to the worktree
 * top. `scope` narrows the lookup (`--global`) for `init --global`, which
 * must not mistake a repo's local setting for the user-wide one.
 */
export function effectiveHooksPath(
  root: string,
  { scope = null }: { scope?: string | null } = {},
): string | null {
  const args = ['config', ...(scope ? [scope] : []), '--path', '--get', 'core.hooksPath'];
  const r = git.git(args, { cwd: root });
  if (!r.ok) return null;
  const value = r.stdout.trim();
  if (!value) return null;
  if (path.isAbsolute(value)) return value;
  const top = git.git(['rev-parse', '--show-toplevel'], { cwd: root });
  return path.resolve(top.ok && top.stdout.trim() ? top.stdout.trim() : root, value);
}

/**
 * The PROMPTLOG_CHAIN_DIR baked into the dispatcher already in `dir`, or
 * null. Re-running `init` overwrites our own dispatchers, and by then
 * core.hooksPath already points at `dir` itself - the directory it replaced
 * is only known from what the first run baked in, so it is carried forward
 * or the previous hooks would silently stop running on the second `init`.
 */
export function bakedChainDir(dir: string): string | null {
  let body: string;
  try {
    body = fs.readFileSync(path.join(dir, 'prepare-commit-msg'), 'utf8');
  } catch {
    return null;
  }
  if (!body.includes(DISPATCHER_MARKER)) return null;
  // Current (Node, fail-open) format: `const chainDir = "<json string>";`.
  const current = /^const chainDir = (.+);\s*$/m.exec(body);
  if (current) {
    try {
      const value = JSON.parse(current[1] as string) as unknown;
      return typeof value === 'string' && value ? value : null;
    } catch {
      return null;
    }
  }
  // Previous (Node, pre-fail-open) format: `'--chain-dir', "<json string>"`
  // as the last argument on the `process.argv.splice(...)` line. Kept so an
  // un-reinitialized dispatcher from before this file's fail-open rewrite
  // still carries its chain forward.
  const js = /'--chain-dir', (.+)\);\s*$/m.exec(body);
  if (js) {
    try {
      const value = JSON.parse(js[1] as string) as unknown;
      return typeof value === 'string' && value ? value : null;
    } catch {
      return null;
    }
  }
  // Old (sh) format, kept so a repo is upgraded without losing its chain: an
  // un-reinitialized dispatcher from before the Node port.
  const sh = /^PROMPTLOG_CHAIN_DIR='(.*)'$/m.exec(body);
  if (!sh) return null;
  const value = (sh[1] as string).replace(/'\\''/g, "'"); // undo the old shQuote
  return value && value !== '__PROMPTLOG_CHAIN_DIR__' ? value : null;
}

/**
 * The absolute promptlog.js path baked into hook file `file` (the argument to
 * `require(...)` in the current Node format, or `PROMPTLOG_JS='...'` in the
 * old sh format), or null when `file` does not hold one of our dispatchers.
 * Used by `doctor` (Grok finding P2): a moved or uninstalled promptlog means
 * the hook file's own `require()` throws before it ever gets to run, so this
 * is the only way left to warn about it.
 */
export function bakedEntryPoint(file: string): string | null {
  let body: string;
  try {
    body = fs.readFileSync(file, 'utf8');
  } catch {
    return null;
  }
  if (!body.includes(DISPATCHER_MARKER)) return null;
  // Current (Node, fail-open) format: `const bakedPath = "<json string>";`.
  const current = /^const bakedPath = (.+);\s*$/m.exec(body);
  if (current) {
    try {
      const value = JSON.parse(current[1] as string) as unknown;
      return typeof value === 'string' && value ? value : null;
    } catch {
      return null;
    }
  }
  // Previous (Node, pre-fail-open) format: a bare `require("<json>");`.
  const js = /^require\((.+)\);\s*$/m.exec(body);
  if (js) {
    try {
      const value = JSON.parse(js[1] as string) as unknown;
      return typeof value === 'string' && value ? value : null;
    } catch {
      return null;
    }
  }
  const sh = /^PROMPTLOG_JS='(.*)'$/m.exec(body);
  if (!sh) return null;
  const value = (sh[1] as string).replace(/'\\''/g, "'"); // undo the old shQuote
  return value && value !== '__PROMPTLOG_JS__' ? value : null;
}

/** Same directory: resolved, `realpath`'d when it exists, case-folded on
 * win32 (`fsutil.canonicalPath`) - so a short 8.3 alias or a case
 * difference in one of the two never reads as a different directory. */
export function samePath(a: string, b: string): boolean {
  return canonicalPath(a) === canonicalPath(b);
}

/**
 * Write the four dispatchers into `dir`, baking in our own entry point and,
 * when `chainDir` is given, the hooks directory core.hooksPath pointed at
 * before promptlog took it over (the dispatcher chains to it).
 */
export function installHooks(
  dir: string,
  { renameExisting = false, chainDir = null }: { renameExisting?: boolean; chainDir?: string | null } = {},
): string[] {
  fs.mkdirSync(dir, { recursive: true });
  const installed: string[] = [];
  for (const name of HOOK_NAMES) {
    const body = hookBody(name, chainDir);
    const target = path.join(dir, name);
    if (renameExisting && fs.existsSync(target)) {
      let isOurs = false;
      try {
        // A distinctive marker, not just "promptlog": a user's hook can
        // legitimately mention the word (or sit in a path that does).
        isOurs = fs.readFileSync(target, 'utf8').includes(DISPATCHER_MARKER);
      } catch {
        isOurs = false;
      }
      // Ours: just overwrite it. Somebody else's (husky, pre-commit, a
      // hand-written hook): rotate it to the first free .legacy slot.
      // Deleting it because `.legacy` happens to be taken would destroy a
      // hook the user installed after us, which a re-run of `init` must
      // never do.
      if (!isOurs) {
        let legacy = `${target}.legacy`;
        for (let n = 1; fs.existsSync(legacy) && n <= 20; n += 1) {
          legacy = `${target}.legacy.${n}`;
        }
        if (!fs.existsSync(legacy)) {
          fs.renameSync(target, legacy);
          try {
            fs.chmodSync(legacy, 0o755);
          } catch {
            /* ignore */
          }
        }
      }
    }
    fs.writeFileSync(target, body, 'utf8');
    fs.chmodSync(target, 0o755);
    installed.push(target);
  }
  return installed;
}

// ------------------------------------------------------------------- hook

/**
 * ONE budget for a whole commit's worth of hooks, not per-hook. pre-commit
 * writes `$GIT_DIR/promptlog-deadline`; the later hooks read it and work
 * with whatever is left; post-commit / post-rewrite remove it. While it is
 * set, `git.ts` clamps every child process timeout to the remainder, so a
 * stuck `git` cannot outlive the budget either. The value itself
 * (`git.HOOK_BUDGET_MS`) is platform-aware - see that constant's comment.
 */

function deadlinePath(root: string): string {
  return path.join(gitDirOf(root), 'promptlog-deadline');
}

/** Where pre-commit leaves the gids for prepare-commit-msg. */
function pendingPath(root: string): string {
  return path.join(gitDirOf(root), 'promptlog-pending');
}

/**
 * Where pre-commit leaves the per-file attribution for post-commit.
 *
 * The evidence is computed against the INDEX, which only exists before the
 * commit; post-commit is where the sha finally exists. Separate from the
 * pending gid file because prepare-commit-msg consumes that one.
 */
function evidencePath(root: string): string {
  return path.join(gitDirOf(root), 'promptlog-attribution');
}

/** The attributor's Map as a plain object, for the pending-evidence file. */
function evidenceObject(linked: Map<string, LinkedEntry>): Record<string, LinkedEntry> {
  const o: Record<string, LinkedEntry> = {};
  for (const [gid, v] of linked) o[gid] = { role: v.role, files: v.files ?? {} };
  return o;
}

function writeEvidence(root: string, linked: Map<string, LinkedEntry>): void {
  try {
    fs.writeFileSync(
      evidencePath(root),
      JSON.stringify({ at: Date.now(), evidence: evidenceObject(linked) }),
      'utf8',
    );
  } catch {
    /* post-commit degrades to role 'unknown' */
  }
}

const LINKED_ENTRY_ROLES = new Set<string>(['contributor', 'committer', 'both', 'unknown']);

function decodeLinkedEntry(v: unknown): LinkedEntry | null {
  const r = rec(v);
  const role = r && str(r.role);
  if (!r || !role || !LINKED_ENTRY_ROLES.has(role)) return null;
  return { role: role as CommitRole, files: decodeFileEvidence(r.files) };
}

/** Read and DELETE the evidence left by pre-commit. Stale is no evidence. */
function takeEvidence(root: string): Record<string, LinkedEntry> | null {
  let payload: unknown = null;
  try {
    payload = JSON.parse(fs.readFileSync(evidencePath(root), 'utf8'));
  } catch {
    payload = null;
  }
  try {
    fs.unlinkSync(evidencePath(root));
  } catch {
    /* ignore */
  }
  const r = rec(payload);
  const evidenceRaw = r ? rec(r.evidence) : null;
  if (!r || !evidenceRaw) return null;
  if (Date.now() - Number(r.at) >= 60000) return null;
  const evidence: Record<string, LinkedEntry> = {};
  for (const [gid, val] of Object.entries(evidenceRaw)) {
    const entry = decodeLinkedEntry(val);
    if (entry) evidence[gid] = entry;
  }
  return evidence;
}

function openBudget(root: string, { create = false }: { create?: boolean } = {}): () => boolean {
  const file = deadlinePath(root);
  let at: number | null = null;
  try {
    const v = Number(fs.readFileSync(file, 'utf8').trim());
    if (Number.isFinite(v) && v > Date.now()) at = v;
  } catch {
    at = null;
  }
  if (at == null) {
    at = Date.now() + git.HOOK_BUDGET_MS;
    if (create) {
      try {
        fs.writeFileSync(file, String(at), 'utf8');
      } catch {
        /* best effort */
      }
    }
  }
  git.setDeadline(at);
  const deadline = at;
  return () => Date.now() >= deadline;
}

function closeBudget(root: string): void {
  git.clearDeadline();
  try {
    fs.unlinkSync(deadlinePath(root));
  } catch {
    /* ignore */
  }
}

/**
 * The one line every budget-caused skip writes, always starting `promptlog:`
 * so it is `grep`-able and so the tests (which read it back out of the
 * commit's captured stderr) can tell "nothing to do" apart from "ran out of
 * time". Never an error - the commit still succeeds - but silent
 * degradation is not diagnosable, so this makes it visible instead.
 */
function noteBudgetSkip(ctx: Ctx, what: string): void {
  err(ctx, `promptlog: hook budget exhausted, skipped ${what}`);
}

function readStdinSync(): string {
  try {
    return fs.readFileSync(0, 'utf8');
  } catch {
    return '';
  }
}

function union(...lists: Array<string[] | undefined>): string[] {
  const seen = new Set<string>();
  const list: string[] = [];
  for (const l of lists) {
    for (const g of l ?? []) {
      if (!g || seen.has(g)) continue;
      seen.add(g);
      list.push(g);
    }
  }
  return list;
}

// ---- what kind of commit is this? ---------------------------------------

/**
 * Is this commit amending HEAD?
 *
 * There is no single signal, so we use every one git actually gives us:
 *
 *  1. `prepare-commit-msg` gets source "commit" with the literal string
 *     `HEAD` for `--amend`, whereas `-C <commit>` / `-c <commit>` pass the
 *     ref the user named (`HEAD~1`, a sha, a branch). That distinguishes the
 *     two cases that otherwise look identical.
 *  2. The git command line, captured by the dispatcher into
 *     PROMPTLOG_GIT_CMD (our parent process is git). This is the only thing
 *     that catches `git commit --amend -m msg`, which reports source
 *     "message" with no sha, exactly like a plain `commit -m`. Advisory:
 *     absent means "not an amend".
 *  3. GIT_REFLOG_ACTION, which git sets for rebase/merge driven commits but
 *     NOT for `git commit` - kept because it costs nothing and is right
 *     when it is present.
 *
 * `pre-commit` has no arguments at all, so there it rests on (2) and (3).
 */
function isAmending(
  ctx: Pick<Ctx, 'env'>,
  { source = null, sha = null }: { source?: string | null; sha?: string | null } = {},
): boolean {
  if (source === 'commit' && sha === 'HEAD') return true;
  const cmd = String(ctx.env.PROMPTLOG_GIT_CMD ?? '');
  if (/(^|\s)--amend(\s|=|$)/.test(cmd)) return true;
  return /\bamend\b/i.test(String(ctx.env.GIT_REFLOG_ACTION ?? ''));
}

function isMerging(root: string): boolean {
  return fs.existsSync(path.join(gitDirOf(root), 'MERGE_HEAD'));
}

/**
 * Start of the window for this commit. On amend, HEAD is the commit being
 * REPLACED, so using its own committer date gives an empty window and the
 * amended commit would silently lose every trailer: use HEAD^ instead.
 */
function windowSince(root: string, { amend = false }: { amend?: boolean } = {}): number | null {
  if (!amend) return git.headCommitTime(root);
  const r = git.git(['log', '-1', '--format=%ct', 'HEAD^'], { cwd: root });
  if (r.ok) {
    const secs = Number.parseInt(r.stdout.trim(), 10);
    if (Number.isFinite(secs)) return secs * 1000000;
  }
  return null; // amending the root commit: the whole session is in scope
}

// ---- collect / stage ----------------------------------------------------

/** `.gitattributes` as it stands, or null when there is none. */
function readGitattributes(root: string): string | null {
  try {
    return fs.readFileSync(path.join(root, '.gitattributes'), 'utf8');
  } catch {
    return null;
  }
}

/**
 * Select, redact, upsert and stage the records for the commit being made.
 *
 * Selection is by evidence now, not by a time window: contributors are the
 * turns that can be shown to have written the staged hunks, plus the
 * committer turn when an agent is the one committing. The per-file evidence
 * is left for post-commit, which is the first hook that knows the sha.
 */
function collectAndStage(
  ctx: Ctx,
  root: string,
  config: StoreConfig,
  overBudget: () => boolean,
  { amend = false }: { amend?: boolean } = {},
): string[] {
  const since = windowSince(root, { amend });
  const { chosen, linked, unattributed } = attributeCommit({
    cwd: ctx.cwd,
    root,
    env: ctx.env,
    agent: str(ctx.env.PROMPTLOG_AGENT) || 'auto',
    session: null,
    since,
  });
  if (!chosen.length) return [];
  if (overBudget()) {
    noteBudgetSkip(ctx, 'record writing for this commit (attribution ran out of time)');
    return [];
  }
  const gids = writeRecords(root, chosen, { config });
  if (!gids.length) return [];
  writeEvidence(root, linked);
  const left = Object.keys(unattributed).length;
  if (left) {
    // Honest, and quiet: one line, never an error. Hand edits and shell
    // work without tier B evidence land here, which is the expected
    // outcome.
    const total = Object.values(unattributed).reduce((a, b) => a + b, 0);
    err(
      ctx,
      `promptlog: ${total} hunk${total === 1 ? '' : 's'} in ${left} file${left === 1 ? '' : 's'} unattributed`,
    );
  }
  // `.gitattributes` is the user's file. We stage it only when this very
  // run changed it (init's merge-driver lines), never blindly: a commit
  // must not smuggle in the user's own unstaged edits to it.
  const attrsBefore = readGitattributes(root);
  if (overBudget()) noteBudgetSkip(ctx, 'README/index regenerate');
  else regenerate(root, config);
  git.git(['add', '--', STORE_DIR], { cwd: root });
  if (readGitattributes(root) !== attrsBefore) {
    git.git(['add', '--', '.gitattributes'], { cwd: root });
  }
  return gids;
}

/**
 * Records that carry no commit sha at all: written by a previous commit
 * that the user then aborted (`GIT_EDITOR=false`), or by `promptlog sync`.
 * They are already staged and correct; they simply belong to THIS commit
 * now. Returns their gids so they get trailers rather than being orphaned
 * forever.
 */
function orphanGids(root: string): string[] {
  return allRecords(root)
    .filter((e) => !e.record.isCommand && !(e.record.commits ?? []).length)
    .map((e) => e.gid);
}

// ---- the four hooks ------------------------------------------------------

/**
 * pre-commit: the only stage at which `git add` still affects the commit
 * being built, so the records are written and staged here.
 */
function hookPreCommit(
  _rest: string[],
  ctx: Ctx,
  root: string,
  config: StoreConfig,
  overBudget: () => boolean,
): number {
  if (isMerging(root)) return 0; // merges are not prompt work
  if (isPartialCommit(ctx, root)) return 0; // temp index: we cannot stage
  const amend = isAmending(ctx);
  const fresh = collectAndStage(ctx, root, config, overBudget, { amend });
  const gids = union(fresh, orphanGids(root));
  if (!gids.length) return 0;
  if (!fresh.length) {
    // Nothing new, but leftovers to carry: make sure the derived files
    // match.
    if (overBudget()) noteBudgetSkip(ctx, 'README/index regenerate for carried-over records');
    else regenerate(root, config);
    git.git(['add', '--', STORE_DIR], { cwd: root });
  }
  try {
    fs.writeFileSync(
      pendingPath(root),
      JSON.stringify({ at: Date.now(), head: git.headSha(root) ?? null, gids }),
      'utf8',
    );
  } catch {
    /* prepare-commit-msg will just redo the selection */
  }
  return 0;
}

/**
 * Read and DELETE the pending gid list. It is keyed to the HEAD it was
 * computed against: without that, a `--no-verify` commit made within a
 * minute of an aborted one would inherit the other commit's gids.
 */
function takePending(root: string): string[] | null {
  const file = pendingPath(root);
  let payload: unknown = null;
  try {
    payload = JSON.parse(fs.readFileSync(file, 'utf8'));
  } catch {
    payload = null;
  }
  try {
    fs.unlinkSync(file);
  } catch {
    /* ignore */
  }
  const r = rec(payload);
  if (!r || !Array.isArray(r.gids)) return null;
  if (Date.now() - Number(r.at) >= 60000) return null;
  const head = git.headSha(root) ?? null;
  if (str(r.head) !== head) return null;
  return arr(r.gids).filter((g): g is string => typeof g === 'string');
}

/** prepare-commit-msg <msgfile> [source] [sha] */
function hookPrepareCommitMsg(
  rest: string[],
  ctx: Ctx,
  root: string,
  config: StoreConfig,
  overBudget: () => boolean,
): number {
  const [msgFile, source, sha] = rest;
  // Always consume the pending file, on every path, so a skipped commit can
  // never leak its gid list into the next one.
  const pending = takePending(root);
  if (!msgFile) return 0;

  const amend = isAmending(ctx, { source, sha });
  if (source === 'merge' || source === 'squash') return 0;
  // A pathspec commit builds a temporary index (GIT_INDEX_FILE points at
  // `next-index-*.lock`, not `$GIT_DIR/index`). pre-commit already skipped
  // it; this hook must skip it too, on EVERY path, or the "redo the work if
  // pre-commit was bypassed" fallback writes and stages records that
  // cannot land in this commit and are left modified afterwards.
  if (isPartialCommit(ctx, root)) return 0;
  // `-C`/`-c <commit>` also reports source "commit" with a sha, but names
  // some other commit and reuses its message and trailers: leave it alone.
  // An amend (sha === 'HEAD') is the one case where we do want to
  // re-derive.
  if (source === 'commit' && sha && !amend) return 0;
  if (isMerging(root)) return 0;

  let gids = pending;
  if (!gids) {
    gids = union(collectAndStage(ctx, root, config, overBudget, { amend }), orphanGids(root));
  }

  let message: string;
  try {
    message = fs.readFileSync(msgFile, 'utf8');
  } catch {
    return 0;
  }
  if (amend) {
    // Keep the trailers the amended message already has, plus the ones
    // HEAD itself carried: `git commit --amend -m msg` REPLACES the
    // message, so the message file is the one place they are not. Then add
    // whatever the (correctly widened) window turned up.
    gids = union(
      git.parseTrailers(message, { cwd: root }),
      git.parseTrailers(git.commitMessage(root, 'HEAD'), { cwd: root }),
      gids,
    );
  }
  if (!gids.length) return 0;

  const next = git.appendTrailers(message, gids, { cwd: root });
  if (next !== message) fs.writeFileSync(msgFile, next, 'utf8');
  return 0;
}

function hookPostCommit(
  _rest: string[],
  ctx: Ctx,
  root: string,
  config: StoreConfig,
  overBudget: () => boolean,
): number {
  if (ctx.env.PROMPTLOG_AMENDING === '1') return 0;
  const sha = git.headSha(root);
  if (!sha) {
    closeBudget(root);
    return 0;
  }
  const gids = git.parseTrailers(git.commitMessage(root, sha), { cwd: root });
  if (!gids.length) {
    closeBudget(root);
    return 0;
  }

  addCommitToGids(root, gids, sha, { evidence: takeEvidence(root) });
  if (overBudget()) noteBudgetSkip(ctx, 'README/index regenerate');
  else regenerate(root, config);

  if (config.notes) git.notesAdd(root, gids, { sha });

  const wantAmend = git.configGet(root, 'promptlog.amend') === 'true';
  if (wantAmend && overBudget()) {
    noteBudgetSkip(
      ctx,
      `promptlog.amend for ${sha.slice(0, 8)} (the commit keeps its evidence, just unamended)`,
    );
  } else if (wantAmend) {
    const dirty = git.git(['status', '--porcelain', '--', STORE_DIR], { cwd: root });
    if (dirty.ok && dirty.stdout.trim()) {
      git.git(['add', '--', STORE_DIR], { cwd: root });
      const amended = git.git(['commit', '--amend', '--no-edit', '--no-verify'], {
        cwd: root,
        env: { ...process.env, PROMPTLOG_AMENDING: '1' },
      });
      // The amend rewrote the commit we JUST recorded, and post-rewrite is
      // suppressed for our own nested git call by the dispatcher's depth
      // guard, so the remap has to happen here or the stored sha stays
      // stale.
      if (amended.ok) {
        const newSha = git.headSha(root);
        if (newSha && newSha !== sha) {
          remapCommits(root, new Map([[sha, newSha]]));
          if (overBudget()) noteBudgetSkip(ctx, 'README/index regenerate after amend');
          else regenerate(root, config);
          git.git(['add', '--', STORE_DIR], { cwd: root });
        }
      }
    }
  }
  closeBudget(root);
  return 0;
}

function hookPostRewrite(
  _rest: string[],
  ctx: Ctx,
  root: string,
  config: StoreConfig,
  overBudget: () => boolean,
): number {
  const mapping = git.parseRewriteStdin(readStdinSync());
  if (!mapping.size) {
    closeBudget(root);
    return 0;
  }
  remapCommits(root, mapping);
  if (overBudget()) noteBudgetSkip(ctx, 'README/index regenerate after rewrite');
  else regenerate(root, config);
  closeBudget(root);
  return 0;
}

export async function hook(args: CommandArgs, ctx: Ctx): Promise<number> {
  const rest = positionalsAfter(args, 'hook');
  const name = rest[0];
  const hookArgs = rest.slice(1);
  try {
    const root = findRepoRoot(ctx.cwd);
    if (!root) return 0;
    if (!git.isEnabled(root)) return 0;
    const config = ensureConfig(root);
    if (config.enabled === false) return 0;

    const overBudget = openBudget(root, { create: name === 'pre-commit' });

    if (name === 'pre-commit') return hookPreCommit(hookArgs, ctx, root, config, overBudget);
    if (name === 'prepare-commit-msg') return hookPrepareCommitMsg(hookArgs, ctx, root, config, overBudget);
    if (name === 'post-commit') return hookPostCommit(hookArgs, ctx, root, config, overBudget);
    if (name === 'post-rewrite') return hookPostRewrite(hookArgs, ctx, root, config, overBudget);
    return 0;
  } catch (e) {
    // Fail open, and fail CLOSED on redaction: when the redactor is
    // unavailable nothing has been written and no trailer is added.
    err(ctx, `promptlog: ${name ?? 'hook'} skipped (${errorMessage(e)})`);
    return 0;
  } finally {
    git.clearDeadline();
  }
}
