// Bundles src/cli.ts into the one file every install channel ships:
// skills/promptlog/scripts/promptlog.js (see docs/DESIGN.md "Layout").
// Readable and unminified on purpose: a user can open what runs.

import { chmodSync } from 'node:fs';
import { build } from 'esbuild';

const outfile = 'skills/promptlog/scripts/promptlog.js';

await build({
  entryPoints: ['src/cli.ts'],
  outfile,
  bundle: true,
  platform: 'node',
  target: 'node18',
  format: 'cjs',
  minify: false,
  legalComments: 'none',
  banner: { js: '#!/usr/bin/env node\n// Generated by `npm run build` from src/ - do not edit.' },
  logLevel: 'warning',
});
chmodSync(outfile, 0o755);
